# Generated by Django 3.2.4 on 2021-07-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(choices=[('Chop suey', 'Chop suey'), ('Pollo frito y papas fritas', 'Pollo frito y papas fritas'), ('Ensalada BBQ con Pork belly', 'Ensalada BBQ con Pork belly'), ('Torta de piña', 'Torta de piña'), ('Torta de merengue de mango', 'Torta de merengue de mango'), ('Jugo de mango', 'Jugo de mango')], max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.pedido')),
            ],
        ),
    ]
