# Generated by Django 3.2.4 on 2021-07-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Registro.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_plato',
            field=models.CharField(max_length=100),
        ),
    ]
