# Generated by Django 3.2.4 on 2021-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('sueldo', models.IntegerField()),
                ('nivel_estudio', models.CharField(choices=[('Educación Basica', 'Educación Basica'), ('Educación Media', 'Educación Media'), ('Educación Superior', 'Educación Superior')], max_length=50)),
            ],
        ),
    ]
